apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-test-pod
spec:
  replicas: 3 # Number of pods to be created
  selector:
    matchLabels:
      name: busybox-test-pod # This is the label that will be used to identify the pods created by this deployment
  template:
    metadata:
      labels:
        name: busybox-test-pod
    spec:
      containers:
      - name: busybox-test-pod
        image: busybox:1.161
        command:
        - sh
        - "-c"
        - echo Hello Team! && sleep 1000 # This will print Hello Team! and then sleep for 3600 seconds. This is a good way to test if the pod is running or not.

        # delete a pod
        # kubectl rollout history deployment/busybox-test-pod
        # kubectl scale deployment/busybox-test-pod --replicas=3
        # change image to busybox:1.161
        # kubectl rollout undo deployment/busybox-test-pod --to-revision=2
        # RollingUpdate strategy
