apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-storageclass
  resources:
      requests:
          storage: 3Gi