# echo -n 'admin' | base64
# echo -n 'password' | base64

# echo 'YWRtaW4=' | base64 --decode
# echo 'cGFzc3dvcmQ=' | base64 --decode

# decoding kubectl  get secret test-secret -o jsonpath='{.data}'
# decoding kubectl  get secret test-secret -o jsonpath='{.data}' | base64 --decode

apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=