apiVersion: v1
kind: Pod
metadata:
  name: volume-test-secret
spec:
  containers:
  - name: test-secret
    image: nginx
    volumeMounts:
    - name: test-volume
      mountPath: /etc/config/secret
  volumes:
  - name: test-volume
    secret:
      secretName: credentials-secret

# kubectl create secret generic credentials-secret --from-file=user.txt --from-file=password.txt